# CI handling matplotlib
name: Matplotlib CI

on:
  # Trigger the workflow on push or pull request events but only for the "main" branch,
  # for given paths
  push:
   branches: [ "main" ]
   paths: ['src/matplotlib/**', 'examples/matplotlib/**']
  pull_request:
   branches: [ "main" ]
   paths: ['src/matplotlib/**', 'examples/matplotlib/**']

  # Allow manual dispatch
  workflow_dispatch:

jobs:
  matplotlib-example:
    runs-on: ubuntu-latest

    steps:
      # Check-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Set up python version and caching using pip
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Set up pip dependencies
        run: |
          pip install numpy scipy matplotlib
          pip install $GITHUB_WORKSPACE

      - name: Create matplotlib example plots
        run: |
          cd $GITHUB_WORKSPACE/examples/matplotlib
          python3 example.py

      - name: Upload plots
        uses: actions/upload-artifact@v4
        with:
          name: matplotlib-example
          path: ${{ github.workspace }}/examples/matplotlib/example.matplotlib.pdf
          if-no-files-found: error
